name = "frontend"
pages_build_output_dir = "dist"
compatibility_date = "2025-12-29"

[vars]
NODE_VERSION = "24.14.0"

[[services]]
binding = "BACKEND"
service = "backend"

[env.preview.vars]
NODE_VERSION = "24.14.0"
VITE_MOCK = "false"

[[env.preview.services]]
binding = "BACKEND"
service = "backend-preview"

[env.production.vars]
NODE_VERSION = "24.14.0"
VITE_MOCK = "false"

[[env.production.services]]
binding = "BACKEND"
service = "backend"
