import { defineConfig } from "vitepress";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

interface TocSection {
  key: string;
  text: string;
  items: { text: string; link: string }[];
}

// Read rather than imported: the file is generated by `npm run mirror` moments
// before this config is evaluated, and a static import would be resolved by the
// bundler against a tree that may not exist yet on a clean checkout.
const toc = JSON.parse(
  readFileSync(new URL("../build/data/toc.json", import.meta.url), "utf8"),
) as { sections: TocSection[]; charter: { text: string; link: string }[] };

const GITHUB = "https://github.com/FantasyWiki/FantasyWiki";

/**
 * The reference tier is not written down here. `scripts/prepare.mjs` derives it
 * from the frontmatter of everything under `docs/`, so a document added to the
 * repository appears in this sidebar on the next build without anyone
 * remembering to come back and add it.
 */
const referenceGroups = toc.sections.map((section) => ({
  text: section.text,
  collapsed: section.key !== "domain",
  items: section.items,
}));

const sidebar = [
  {
    text: "Orientation",
    items: [
      { text: "What FantasyWiki is", link: "/overview/what-is-fantasywiki.html" },
      { text: "Requirements", link: "/overview/requirements.html" },
      { text: "The Docs Atlas", link: "/#the-docs-atlas" },
      { text: "Coverage", link: "/#coverage" },
    ],
  },
  {
    text: "System",
    items: [
      { text: "Architecture overview", link: "/architecture/" },
      { text: "Data flow", link: "/architecture/data-flow.html" },
      { text: "Data model", link: "/architecture/data-model.html" },
      { text: "Frontend", link: "/architecture/frontend.html" },
      { text: "API reference", link: "/api.html" },
      { text: "Deployment", link: "/architecture/deployment.html" },
    ],
  },
  {
    text: "Quality",
    items: [
      { text: "Test strategy", link: "/quality/testing.html" },
      { text: "Continuous delivery", link: "/quality/ci-cd.html" },
      { text: "About this site", link: "/about-this-site.html" },
    ],
  },
  {
    text: "Reference",
    items: [{ text: "Documentation index", link: "/docs/" }, ...referenceGroups],
  },
  {
    text: "Project charter",
    collapsed: true,
    items: toc.charter,
  },
];

export default defineConfig({
  title: "FantasyWiki",
  description:
    "Technical documentation for FantasyWiki — a fantasy league played with Wikipedia articles.",
  lang: "en-GB",

  // The site is served from https://fantasywiki.github.io/FantasyWiki/, so every
  // asset URL has to carry the repository name.
  base: "/FantasyWiki/",

  // Everything generated sits under `build/`, which the repository root
  // gitignores by name. `srcDir` is the markdown mirror, not the authored
  // pages — those are one of its two inputs.
  srcDir: "./build/content",
  outDir: "./build/dist",
  cacheDir: "./build/cache",
  cleanUrls: false,

  // Left on deliberately: it is the only automated check that the mirror in
  // `scripts/prepare.mjs` rewrote every link that leaves the docs tree. The one
  // exemption is the dev server's own address, which the local-development docs
  // quote as a URL and which is unreachable by definition from a build machine.
  ignoreDeadLinks: [/^https?:\/\/localhost/, /^https?:\/\/127\.0\.0\.1/],

  lastUpdated: false,
  metaChunk: true,

  head: [
    ["link", { rel: "icon", type: "image/png", href: "/FantasyWiki/logo.png" }],
    ["link", { rel: "preconnect", href: "https://fonts.googleapis.com" }],
    ["link", { rel: "preconnect", href: "https://fonts.gstatic.com", crossorigin: "" }],
    [
      "link",
      {
        rel: "stylesheet",
        href: "https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital,wght@0,400;0,700;1,400&family=Source+Sans+3:ital,wght@0,300..700;1,300..700&family=JetBrains+Mono:wght@400;500&display=swap",
      },
    ],
    ["meta", { name: "theme-color", content: "#1e7e50" }],
    ["meta", { property: "og:type", content: "website" }],
    ["meta", { property: "og:title", content: "FantasyWiki — technical documentation" }],
    [
      "meta",
      {
        property: "og:description",
        content: "How a fantasy league played with Wikipedia articles is built, decided and shipped.",
      },
    ],
  ],

  markdown: {
    theme: { light: "github-light", dark: "github-dark" },
    lineNumbers: false,
    config(md) {
      // Mermaid blocks become a component rather than a code block. The source
      // is base64-encoded on the way through so that quotes, angle brackets and
      // newlines survive being carried in a Vue prop.
      const fence = md.renderer.rules.fence!;
      md.renderer.rules.fence = (tokens, index, options, env, self) => {
        const token = tokens[index];
        if (token.info.trim().split(/\s+/)[0] === "mermaid") {
          const encoded = Buffer.from(token.content, "utf8").toString("base64");
          return `<Mermaid graph="${encoded}" />`;
        }
        return fence(tokens, index, options, env, self);
      };
    },
  },

  vite: {
    resolve: {
      alias: {
        "@generated": fileURLToPath(new URL("../build/data", import.meta.url)),
      },
    },
  },

  themeConfig: {
    logo: "/logo.png",
    siteTitle: "FantasyWiki documentation",

    nav: [
      { text: "Overview", link: "/overview/what-is-fantasywiki.html" },
      { text: "Architecture", link: "/architecture/" },
      { text: "API", link: "/api.html" },
      { text: "Reference", link: "/docs/" },
      { text: "Atlas", link: "/#the-docs-atlas" },
      { text: "Coverage", link: "/#coverage" },
      {
        text: "Play",
        items: [
          { text: "Live app", link: "https://fantasywiki.pages.dev" },
          { text: "Report a problem", link: `${GITHUB}/issues/new/choose` },
        ],
      },
    ],

    sidebar,

    socialLinks: [{ icon: "github", link: GITHUB }],

    search: { provider: "local" },

    outline: { level: [2, 3], label: "On this page" },

    // Mirrored pages carry the path of the file they were copied from, so the
    // edit link points at the document that is actually the source of truth
    // rather than at the generated copy nobody should edit.
    //
    // The URL is written out rather than interpolated from `GITHUB`: VitePress
    // serialises this function into the client bundle, and a closure variable
    // does not survive the trip.
    editLink: {
      pattern: ({ frontmatter }: { frontmatter: Record<string, unknown> }) =>
        `https://github.com/FantasyWiki/FantasyWiki/edit/master/${frontmatter.source ?? "README.md"}`,
      text: "Edit this page on GitHub",
    },

    docFooter: { prev: "Previous", next: "Next" },

    footer: {
      message: `Built from the repository's own documentation. <a href="${GITHUB}">Source on GitHub</a>.`,
      copyright: "AGPL-3.0 · Marco Galeri & Luca Patrignani",
    },
  },
});
