name: ci-cd
on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'master') }}

jobs:
  dispatcher:
    runs-on: ubuntu-24.04
    if: >-
      github.event_name != 'pull_request'
      || github.event.pull_request.head.repo.full_name != github.repository
      || startsWith(github.head_ref, 'dependabot/')
    steps:
      - run: 'true'
  check:
    needs:
      - dispatcher
    uses: ./.github/workflows/check.yml
    secrets: inherit
    permissions:
      contents: write
      packages: write

  coverage:
    needs:
      - dispatcher
    uses: ./.github/workflows/backend-coverage.yml
    secrets: inherit
    permissions:
      contents: write

  deploy:
    needs:
      - check
      - coverage
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    permissions:
      contents: write
      packages: write
